import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{vue,ts}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      colors: {
        ui: {
          canvas: 'rgb(var(--rw-background) / <alpha-value>)',
          sidebar: 'rgb(var(--rw-sidebar) / <alpha-value>)',
          surface: 'rgb(var(--rw-surface) / <alpha-value>)',
          elevated: 'rgb(var(--rw-surface-elevated) / <alpha-value>)',
          muted: 'rgb(var(--rw-surface-muted) / <alpha-value>)',
          hover: 'rgb(var(--rw-surface-hover) / <alpha-value>)',
          selected: 'rgb(var(--rw-surface-selected) / <alpha-value>)',
          border: 'rgb(var(--rw-border) / <alpha-value>)',
          'border-strong': 'rgb(var(--rw-border-strong) / <alpha-value>)',
          divider: 'rgb(var(--rw-divider) / <alpha-value>)',
          text: 'rgb(var(--rw-text-primary) / <alpha-value>)',
          'text-secondary': 'rgb(var(--rw-text-secondary) / <alpha-value>)',
          mutedText: 'rgb(var(--rw-text-muted) / <alpha-value>)',
          icon: 'rgb(var(--rw-icon) / <alpha-value>)',
          input: 'rgb(var(--rw-input-background) / <alpha-value>)',
          'input-border': 'rgb(var(--rw-input-border) / <alpha-value>)',
          'input-hover': 'rgb(var(--rw-input-hover) / <alpha-value>)',
          'input-focus': 'rgb(var(--rw-input-focus) / <alpha-value>)',
          dropdown: 'rgb(var(--rw-dropdown-background) / <alpha-value>)',
          'dropdown-hover': 'rgb(var(--rw-dropdown-hover) / <alpha-value>)',
          'dropdown-selected': 'rgb(var(--rw-dropdown-selected) / <alpha-value>)',
          overlay: 'rgb(var(--rw-overlay) / <alpha-value>)',
          disabled: 'rgb(var(--rw-disabled-background) / <alpha-value>)',
          'disabled-text': 'rgb(var(--rw-disabled-text) / <alpha-value>)',
          focus: 'rgb(var(--rw-focus-ring) / <alpha-value>)',
        },
        white: 'rgb(var(--rw-white) / <alpha-value>)',
        slate: {
          50: 'rgb(var(--rw-slate-50) / <alpha-value>)',
          100: 'rgb(var(--rw-slate-100) / <alpha-value>)',
          200: 'rgb(var(--rw-slate-200) / <alpha-value>)',
          300: 'rgb(var(--rw-slate-300) / <alpha-value>)',
          400: 'rgb(var(--rw-slate-400) / <alpha-value>)',
          500: 'rgb(var(--rw-slate-500) / <alpha-value>)',
          600: 'rgb(var(--rw-slate-600) / <alpha-value>)',
          700: 'rgb(var(--rw-slate-700) / <alpha-value>)',
          800: 'rgb(var(--rw-slate-800) / <alpha-value>)',
          900: 'rgb(var(--rw-slate-900) / <alpha-value>)',
          950: 'rgb(var(--rw-slate-950) / <alpha-value>)',
        },
        app: {
          light: 'rgb(var(--rw-app-content) / <alpha-value>)',
          dark: 'rgb(var(--rw-app-content) / <alpha-value>)',
          content: 'rgb(var(--rw-app-content) / <alpha-value>)',
          sidebar: 'rgb(var(--rw-app-sidebar) / <alpha-value>)',
          panel: 'rgb(var(--rw-app-panel) / <alpha-value>)',
          elevated: 'rgb(var(--rw-app-elevated) / <alpha-value>)',
          hover: 'rgb(var(--rw-app-hover) / <alpha-value>)',
          border: 'rgb(var(--rw-app-border) / <alpha-value>)',
          muted: 'rgb(var(--rw-app-muted) / <alpha-value>)',
          foreground: 'rgb(var(--rw-app-text) / <alpha-value>)',
        },
        success: {
          50: 'rgb(var(--rw-success-50) / <alpha-value>)',
          100: 'rgb(var(--rw-success-100) / <alpha-value>)',
          400: 'rgb(var(--rw-success-400) / <alpha-value>)',
          500: 'rgb(var(--rw-success-500) / <alpha-value>)',
          600: 'rgb(var(--rw-success-600) / <alpha-value>)',
        },
        danger: {
          50: 'rgb(var(--rw-danger-50) / <alpha-value>)',
          100: 'rgb(var(--rw-danger-100) / <alpha-value>)',
          400: 'rgb(var(--rw-danger-400) / <alpha-value>)',
          500: 'rgb(var(--rw-danger-500) / <alpha-value>)',
          600: 'rgb(var(--rw-danger-600) / <alpha-value>)',
        },
        warning: {
          50: 'rgb(var(--rw-warning-50) / <alpha-value>)',
          100: 'rgb(var(--rw-warning-100) / <alpha-value>)',
          400: 'rgb(var(--rw-warning-400) / <alpha-value>)',
          600: 'rgb(var(--rw-warning-600) / <alpha-value>)',
        },
        info: {
          50: 'rgb(var(--rw-info-50) / <alpha-value>)',
          100: 'rgb(var(--rw-info-100) / <alpha-value>)',
          400: 'rgb(var(--rw-info-400) / <alpha-value>)',
          600: 'rgb(var(--rw-info-600) / <alpha-value>)',
        },
        surface: {
          50: 'rgb(var(--rw-slate-50) / <alpha-value>)',
          100: 'rgb(var(--rw-slate-100) / <alpha-value>)',
          200: 'rgb(var(--rw-slate-200) / <alpha-value>)',
          900: 'rgb(var(--rw-slate-900) / <alpha-value>)',
        },
      },
      boxShadow: {
        soft: 'var(--rw-shadow-sm)',
        popover: 'var(--rw-shadow-popover)',
        modal: 'var(--rw-shadow-modal)',
      },
    },
  },
  plugins: [],
} satisfies Config
